### ISSUE TITLE
Support basic auth to connect to a schema registry when generating C# code from Avro

### ISSUE THREAD

**Issue by skovalyova** [ch-robinson/dotnet-avro#150]
Let's assume I want to generate a C# class from an AVRO schema which persists in a schema registry protected with basic auth. 

[The documentation](https://engineering.chrobinson.com/dotnet-avro/cli/generate) does not describe any arguments to pass username and password. Obviously, I get 401 status code trying to connect to the registry:
```
dotnet avro generate --id 42 --registry-url https://some.url
```

Output:
```
Unhandled exception. Confluent.SchemaRegistry.SchemaRegistryException: Unauthorized; error code: 401
   at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest)
   at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
   at Confluent.SchemaRegistry.RestService.GetSchemaAsync(Int32 id, String format)
   at Confluent.SchemaRegistry.CachedSchemaRegistryClient.GetSchemaAsync(Int32 id, String format)
   at Chr.Avro.Cli.SchemaResolutionOptionExtensions.ResolveSchema(ISchemaResolutionOptions options) in /home/runner/work/dotnet-avro/dotnet-avro/src/Chr.Avro.Cli/SchemaResolutionOptions.cs:line 57
   at Chr.Avro.Cli.GenerateCodeVerb.Run() in /home/runner/work/dotnet-avro/dotnet-avro/src/Chr.Avro.Cli/Verb.cs:line 141
   at Chr.Avro.Cli.Verb.Execute() in /home/runner/work/dotnet-avro/dotnet-avro/src/Chr.Avro.Cli/Verb.cs:line 21
   at Chr.Avro.Cli.Program.<Main>(String[] args)
```

I would like to request ability to connect to a schema registry with the basic authentication when using `generate` CLI command.

**Comment by dstelljes** [comment]
This will be supported in 7.2.0 with the `--registry-config` flag:

```
dotnet avro generate --id 42 --registry-config schema.registry.basic.auth.user.info=username:password --registry-url https://some.url
```

**Comment by skovalyova** [comment]
@dstelljes thank you for this change! Could you please describe it in the documentation?
https://engineering.chrobinson.com/dotnet-avro/cli/generate/

**Comment by dstelljes** [comment]
Yes, added with #159.
