### ISSUE TITLE
Spark throw exception when read Avor file using Chr.Avro serialize 

### ISSUE THREAD

**Issue by xichenAiguang** [ch-robinson/dotnet-avro#156]
I met an issue when try to use Spark reading Avro, below is my code to generate Avro data file using Chr.Avro serializer

` 
  class MyClass
    {
        public Decimal MyDecimal { get; set; }
        public bool MyBool { get; set; }
        public long? MyLong { get; set; }
        public DateTime? MyDateTime { get; set; }
        public string MyString { get; set; }
        public byte MyByte { get; set; }
        public short MyShort { get; set; }
    }
`

            var builder = new SchemaBuilder(TemporalBehavior.EpochMicroseconds);
            var schema = builder.BuildSchema<MyClass>();
            var writer = new JsonSchemaWriter();

            MyClass myClass = new MyClass();
            myClass.MyDateTime = DateTime.UtcNow;
            myClass.MyString = "aiguang";
            myClass.MyShort = 123;

            var serializer = new BinarySerializerBuilder().BuildSerializer<MyClass>(schema);
            var bytes = serializer.Serialize(myClass);
            File.WriteAllBytes(@"E:\test.avro", bytes);`

the following code is my spark code
`val df = spark.read.format("com.databricks.spark.avro").load("test.avro")
df.show(10, false)`

Exception:

> Caused by: java.io.IOException: Not an Avro data file
	at org.apache.spark.sql.avro.AvroFileFormat$.openAvroReader(AvroFileFormat.scala:210)
	at org.apache.spark.sql.avro.AvroUtils$.$anonfun$inferAvroSchemaFromFiles$3(AvroUtils.scala:139)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2807)

Any suggestions? Thanks in advance

**Comment by dstelljes** [comment]
Spark expects that Avro files follow the [Object Container File](https://avro.apache.org/docs/1.10.2/spec.html#Object+Container+Files) format. Presently, Chr.Avro doesn’t support that format. As a workaround, you could manually build an OCF using the information in the spec, or you could read records from Kafka. I’ll leave this issue open as a feature request.

See also https://github.com/ch-robinson/dotnet-avro/discussions/148.

**Comment by PauloHMattos** [comment]
Hey @dstelljes,

I've recently implemented this for an internal library at my company that uses Chr.Avro. I would be glad to contribute it as a native feature for this library.

I would just need some direction on how you envision the public API. Our internal use of Chr.Avro is wrapped in a helper class, so designing the OCF implementation for general public usability wasn't our primary focus.
Let me know if you'd be open to a PR!
