### ISSUE TITLE
Method not found exception

### ISSUE THREAD

**Issue by mihaimyh** [ch-robinson/dotnet-avro#229]
Updating Confluent.Kafka to version 1.9.3 there is an exception
```
Confluent.Kafka.ProduceException`2[Confluent.Kafka.Null,NightsWatch.Utils.Contracts.Models.WebServiceMessage]: Local: Value serialization error
 ---> System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Int32> Confluent.SchemaRegistry.ISchemaRegistryClient.RegisterSchemaAsync(System.String, Confluent.SchemaRegistry.Schema)'.
   at Chr.Avro.Confluent.AsyncSchemaRegistrySerializer`1.<SerializeAsync>b__29_0(String subject)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Chr.Avro.Confluent.AsyncSchemaRegistrySerializer`1.<SerializeAsync>b__29_0(String subject)
   at Chr.Avro.Confluent.AsyncSchemaRegistrySerializer`1.SerializeAsync(T data, SerializationContext context)
   at Confluent.Kafka.Producer`2.ProduceAsync(TopicPartition topicPartition, Message`2 message, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

It seems this was introduced by https://github.com/confluentinc/confluent-kafka-dotnet/commit/7567e89322e0e4f11a4933dccd0b73362c1301e5 where the `RegisterSchemaAsync` method has been changed by adding a bool.

![image](https://user-images.githubusercontent.com/549272/190268776-e9dba57f-753d-4f53-890c-3ca9d426b423.png)

**Comment by dstelljes** [comment]
Thanks for the report! Chr.Avro 9.2.0 will target Confluent.SchemaRegistry >= 1.9.3.
