### ISSUE TITLE
SchemaRegistryException

### ISSUE THREAD

**Issue by mihaimyh** [ch-robinson/dotnet-avro#318]
Getting the following exception while trying produce to Kafka:

```
Confluent.SchemaRegistry.SchemaRegistryException: Unrecognized field: metadata; error code: 422
         at Confluent.SchemaRegistry.RestService.ExecuteOnOneInstanceAsync(Func`1 createRequest)
         at Confluent.SchemaRegistry.RestService.RequestAsync[T](String endPoint, HttpMethod method, Object[] jsonBody)
         at Confluent.SchemaRegistry.RestService.RegisterSchemaAsync(String subject, Schema schema, Boolean normalize)
         at Confluent.SchemaRegistry.CachedSchemaRegistryClient.RegisterSchemaAsync(String subject, Schema schema, Boolean normalize)
         at Chr.Avro.Confluent.AsyncSchemaRegistrySerializer`1.<SerializeAsync>b__29_0(String subject)
         at Chr.Avro.Confluent.AsyncSchemaRegistrySerializer`1.SerializeAsync(T data, SerializationContext context)
         at KafkaFlow.Middlewares.Serializer.SerializerProducerMiddleware.Invoke(IMessageContext context, MiddlewareDelegate next)
         at KafkaFlow.Producers.MessageProducer.ProduceAsync(String topic, Object messageKey, Object messageValue, IMessageHeaders headers, Nullable`1 partition)
         at KafkaFlow.Producers.MessageProducer.ProduceAsync(String topic, Object messageKey, Object messageValue, IMessageHeaders headers, Nullable`1 partition)
         at KafkaFlowProducer.Worker.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\CC16JG\source\repos\KafkaFlowDemo\KafkaFlowProducer\Worker.cs:line 28
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

"Chr.Avro.Confluent" Version="10.4.0"

**Comment by dstelljes** [comment]
Apologies for the delayed response—this is actually an issue with Confluent.SchemaRegistry; your Registry is out of date and rejects the additional metadata fields the client is sending.
